# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'aoo_mode.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1200, 800)
        self.bgwidget = QtWidgets.QWidget(Dialog)
        self.bgwidget.setGeometry(QtCore.QRect(0, 0, 1200, 800))
        self.bgwidget.setStyleSheet("QWidget#bgwidget{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgba(0, 85, 9, 255), stop:1 rgba(255, 147, 147, 255));}")
        self.bgwidget.setObjectName("bgwidget")
        self.label = QtWidgets.QLabel(self.bgwidget)
        self.label.setGeometry(QtCore.QRect(420, 0, 481, 111))
        self.label.setStyleSheet("font: 24pt \"Arial\"; color:rgb(255, 255, 255)\n"
"")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.bgwidget)
        self.label_2.setGeometry(QtCore.QRect(430, 100, 451, 111))
        self.label_2.setStyleSheet("font: 18pt \"Arial\"; color:rgb(255, 255, 255)\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.bgwidget)
        self.label_3.setGeometry(QtCore.QRect(1080, 25, 241, 51))
        self.label_3.setStyleSheet("font: 10pt \"Arial\"; color:rgb(0, 255, 0)\n"
"")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.bgwidget)
        self.label_4.setGeometry(QtCore.QRect(1060, 25, 241, 51))
        self.label_4.setStyleSheet("font: 10pt \"Arial\"; color:rgb(255, 0, 0)\n"
"")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.bgwidget)
        self.label_5.setGeometry(QtCore.QRect(920, 25, 241, 51))
        self.label_5.setStyleSheet("font: 10pt \"Arial\"; color:rgb(0, 0, 0)\n"
"")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.bgwidget)
        self.label_6.setGeometry(QtCore.QRect(430, 200, 161, 41))
        self.label_6.setStyleSheet("font: 12pt \"Arial\"; color:rgb(255, 255, 255)\n"
"")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.bgwidget)
        self.label_7.setGeometry(QtCore.QRect(430, 275, 151, 51))
        self.label_7.setStyleSheet("font: 12pt \"Arial\"; color:rgb(255, 255, 255)\n"
"")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.bgwidget)
        self.label_8.setGeometry(QtCore.QRect(430, 350, 141, 41))
        self.label_8.setStyleSheet("font: 12pt \"Arial\"; color:rgb(255, 255, 255)\n"
"")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.bgwidget)
        self.label_9.setGeometry(QtCore.QRect(430, 425, 161, 41))
        self.label_9.setStyleSheet("font: 12pt \"Arial\"; color:rgb(255, 255, 255)\n"
"")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.bgwidget)
        self.label_10.setGeometry(QtCore.QRect(430, 575, 211, 41))
        self.label_10.setStyleSheet("font: 12pt \"Arial\"; color:rgb(255, 255, 255)\n"
"")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.bgwidget)
        self.label_11.setGeometry(QtCore.QRect(430, 500, 151, 41))
        self.label_11.setStyleSheet("font: 12pt \"Arial\"; color:rgb(255, 255, 255)\n"
"")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.bgwidget)
        self.label_12.setGeometry(QtCore.QRect(430, 640, 341, 61))
        self.label_12.setStyleSheet("font: 12pt \"Arial\"; color:rgb(255, 255, 255)\n"
"")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.bgwidget)
        self.label_13.setGeometry(QtCore.QRect(840, 100, 451, 111))
        self.label_13.setStyleSheet("font: 14pt \"Arial\"; color:rgb(255, 255, 255)\n"
"")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.bgwidget)
        self.label_14.setGeometry(QtCore.QRect(1040, 100, 451, 111))
        self.label_14.setStyleSheet("font: 14pt \"Arial\"; color:rgb(255, 255, 255)\n"
"")
        self.label_14.setObjectName("label_14")
        self.line = QtWidgets.QFrame(self.bgwidget)
        self.line.setGeometry(QtCore.QRect(-13, 90, 1321, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.bgwidget)
        self.line_2.setGeometry(QtCore.QRect(370, -10, 21, 861))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.ApplyChanges = QtWidgets.QPushButton(self.bgwidget)
        self.ApplyChanges.setGeometry(QtCore.QRect(970, 730, 211, 51))
        self.ApplyChanges.setStyleSheet("border-radius: 20px;\n"
"color: rgb(0,0,0);\n"
"background-color: rgb(255, 255, 216);\n"
"font: 12pt \"Arial\";")
        self.ApplyChanges.setObjectName("ApplyChanges")
        self.ResetChanges = QtWidgets.QPushButton(self.bgwidget)
        self.ResetChanges.setGeometry(QtCore.QRect(740, 730, 211, 51))
        self.ResetChanges.setStyleSheet("border-radius: 20px;\n"
"color: rgb(0,0,0);\n"
"background-color: rgb(255, 216, 216);\n"
"font: 12pt \"Arial\";")
        self.ResetChanges.setObjectName("ResetChanges")
        self.checkBox = QtWidgets.QCheckBox(self.bgwidget)
        self.checkBox.setGeometry(QtCore.QRect(980, 700, 231, 20))
        self.checkBox.setObjectName("checkBox")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.bgwidget)
        self.doubleSpinBox.setGeometry(QtCore.QRect(1050, 210, 62, 22))
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.bgwidget)
        self.doubleSpinBox_2.setGeometry(QtCore.QRect(1050, 285, 62, 22))
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.bgwidget)
        self.doubleSpinBox_3.setGeometry(QtCore.QRect(1050, 360, 62, 22))
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.bgwidget)
        self.doubleSpinBox_4.setGeometry(QtCore.QRect(1050, 435, 62, 22))
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.doubleSpinBox_5 = QtWidgets.QDoubleSpinBox(self.bgwidget)
        self.doubleSpinBox_5.setGeometry(QtCore.QRect(1050, 510, 62, 22))
        self.doubleSpinBox_5.setObjectName("doubleSpinBox_5")
        self.doubleSpinBox_6 = QtWidgets.QDoubleSpinBox(self.bgwidget)
        self.doubleSpinBox_6.setGeometry(QtCore.QRect(1050, 660, 62, 22))
        self.doubleSpinBox_6.setObjectName("doubleSpinBox_6")
        self.doubleSpinBox_7 = QtWidgets.QDoubleSpinBox(self.bgwidget)
        self.doubleSpinBox_7.setGeometry(QtCore.QRect(1050, 585, 62, 22))
        self.doubleSpinBox_7.setObjectName("doubleSpinBox_7")
        self.aai = QtWidgets.QPushButton(self.bgwidget)
        self.aai.setGeometry(QtCore.QRect(10, 240, 351, 51))
        self.aai.setStyleSheet("border-radius: 20px;\n"
"color: rgb(0,0,0);\n"
"background-color: rgb(255, 255, 216);\n"
"font: 12pt \"Arial\";")
        self.aai.setObjectName("aai")
        self.LRL_Current = QtWidgets.QLabel(self.bgwidget)
        self.LRL_Current.setGeometry(QtCore.QRect(840, 210, 71, 21))
        self.LRL_Current.setStyleSheet("color: rgb(255,255,255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.LRL_Current.setObjectName("LRL_Current")
        self.URL_Current = QtWidgets.QLabel(self.bgwidget)
        self.URL_Current.setGeometry(QtCore.QRect(840, 285, 71, 21))
        self.URL_Current.setStyleSheet("color: rgb(255,255,255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.URL_Current.setObjectName("URL_Current")
        self.AA_Current = QtWidgets.QLabel(self.bgwidget)
        self.AA_Current.setGeometry(QtCore.QRect(840, 360, 71, 21))
        self.AA_Current.setStyleSheet("color: rgb(255,255,255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.AA_Current.setObjectName("AA_Current")
        self.APW_Current = QtWidgets.QLabel(self.bgwidget)
        self.APW_Current.setGeometry(QtCore.QRect(840, 435, 71, 21))
        self.APW_Current.setStyleSheet("color: rgb(255,255,255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.APW_Current.setObjectName("APW_Current")
        self.AS_Current = QtWidgets.QLabel(self.bgwidget)
        self.AS_Current.setGeometry(QtCore.QRect(840, 510, 71, 21))
        self.AS_Current.setStyleSheet("color: rgb(255,255,255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.AS_Current.setObjectName("AS_Current")
        self.ARP_Current = QtWidgets.QLabel(self.bgwidget)
        self.ARP_Current.setGeometry(QtCore.QRect(840, 585, 71, 21))
        self.ARP_Current.setStyleSheet("color: rgb(255,255,255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.ARP_Current.setObjectName("ARP_Current")
        self.PVARP_Current = QtWidgets.QLabel(self.bgwidget)
        self.PVARP_Current.setGeometry(QtCore.QRect(840, 660, 71, 21))
        self.PVARP_Current.setStyleSheet("color: rgb(255,255,255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.PVARP_Current.setObjectName("PVARP_Current")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Atrium Pacing Mode(AOO)"))
        self.label_2.setText(_translate("Dialog", "Mode Parameters:"))
        self.label_3.setText(_translate("Dialog", "Connected"))
        self.label_4.setText(_translate("Dialog", "Disconnected"))
        self.label_5.setText(_translate("Dialog", "Pacemaker:"))
        self.label_6.setText(_translate("Dialog", "Lower Rate Limit"))
        self.label_7.setText(_translate("Dialog", "Upper Rate Limit"))
        self.label_8.setText(_translate("Dialog", "Atrial Amplitude"))
        self.label_9.setText(_translate("Dialog", "Atrial Pulse Width"))
        self.label_10.setText(_translate("Dialog", "Atrial Refractory Period"))
        self.label_11.setText(_translate("Dialog", "Atrial Sensitivity"))
        self.label_12.setText(_translate("Dialog", "Post Ventrical Atrial Refractory Period"))
        self.label_13.setText(_translate("Dialog", "Current"))
        self.label_14.setText(_translate("Dialog", "Updated"))
        self.ApplyChanges.setText(_translate("Dialog", "Apply Changes"))
        self.ResetChanges.setText(_translate("Dialog", "Reset Changes"))
        self.checkBox.setText(_translate("Dialog", "I have reviewed my changes "))
        self.aai.setText(_translate("Dialog", "AAI Mode"))
        self.LRL_Current.setText(_translate("Dialog", "0"))
        self.URL_Current.setText(_translate("Dialog", "0"))
        self.AA_Current.setText(_translate("Dialog", "0"))
        self.APW_Current.setText(_translate("Dialog", "0"))
        self.AS_Current.setText(_translate("Dialog", "0"))
        self.ARP_Current.setText(_translate("Dialog", "0"))
        self.PVARP_Current.setText(_translate("Dialog", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
