# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_user.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1200, 803)
        self.bgwidget = QtWidgets.QWidget(Dialog)
        self.bgwidget.setGeometry(QtCore.QRect(0, 0, 1200, 800))
        self.bgwidget.setStyleSheet("QWidget#bgwidget{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 85, 9, 255), stop:1 rgba(255, 147, 147, 255));}")
        self.bgwidget.setObjectName("bgwidget")
        self.label = QtWidgets.QLabel(self.bgwidget)
        self.label.setGeometry(QtCore.QRect(440, 60, 261, 111))
        self.label.setStyleSheet("font: 28pt \"Arial\"; color:rgb(255, 255, 255)\n"
"")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.bgwidget)
        self.label_2.setGeometry(QtCore.QRect(450, 140, 281, 111))
        self.label_2.setStyleSheet("font: 12pt \"Arial\"; color:rgb(255, 255, 255)\n"
"")
        self.label_2.setObjectName("label_2")
        self.register_2 = QtWidgets.QPushButton(self.bgwidget)
        self.register_2.setGeometry(QtCore.QRect(480, 510, 161, 51))
        self.register_2.setStyleSheet("border-radius: 20px;\n"
"color: rgb(0,0,0);\n"
"background-color: rgb(255, 255, 216);\n"
"font: 16pt \"Arial\";")
        self.register_2.setObjectName("register_2")
        self.username = QtWidgets.QLineEdit(self.bgwidget)
        self.username.setGeometry(QtCore.QRect(450, 260, 231, 41))
        self.username.setStyleSheet("font: 8pt \"Arial\";\n"
"")
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(self.bgwidget)
        self.password.setGeometry(QtCore.QRect(450, 350, 231, 41))
        self.password.setStyleSheet("font: 8pt \"Arial\";")
        self.password.setObjectName("password")
        self.label_3 = QtWidgets.QLabel(self.bgwidget)
        self.label_3.setGeometry(QtCore.QRect(450, 220, 451, 41))
        self.label_3.setStyleSheet("font: 10pt \"Arial\"; color:rgb(255, 255, 255)\n"
"")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.bgwidget)
        self.label_4.setGeometry(QtCore.QRect(450, 310, 451, 41))
        self.label_4.setStyleSheet("font: 10pt \"Arial\"; color:rgb(255, 255, 255)\n"
"")
        self.label_4.setObjectName("label_4")
        self.password_confirm = QtWidgets.QLineEdit(self.bgwidget)
        self.password_confirm.setGeometry(QtCore.QRect(450, 440, 231, 41))
        self.password_confirm.setStyleSheet("font: 8pt \"Arial\";")
        self.password_confirm.setObjectName("password_confirm")
        self.label_5 = QtWidgets.QLabel(self.bgwidget)
        self.label_5.setGeometry(QtCore.QRect(450, 400, 451, 41))
        self.label_5.setStyleSheet("font: 10pt \"Arial\"; color:rgb(255, 255, 255)\n"
"")
        self.label_5.setObjectName("label_5")
        self.invalid_up2 = QtWidgets.QLabel(self.bgwidget)
        self.invalid_up2.setGeometry(QtCore.QRect(450, 475, 451, 41))
        self.invalid_up2.setStyleSheet("font: 8pt \"Arial\"; color:rgb(255, 0, 0)\n"
"")
        self.invalid_up2.setText("")
        self.invalid_up2.setObjectName("invalid_up2")
        self.back = QtWidgets.QPushButton(self.bgwidget)
        self.back.setGeometry(QtCore.QRect(480, 580, 161, 51))
        self.back.setStyleSheet("border-radius: 20px;\n"
"color: rgb(0,0,0);\n"
"background-color: rgb(255, 216, 216);\n"
"font: 16pt \"Arial\";")
        self.back.setObjectName("back")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Registration"))
        self.label_2.setText(_translate("Dialog", "Please Register Patient below."))
        self.register_2.setText(_translate("Dialog", "Register"))
        self.label_3.setText(_translate("Dialog", "Username"))
        self.label_4.setText(_translate("Dialog", "Password"))
        self.label_5.setText(_translate("Dialog", "Confirm Password"))
        self.back.setText(_translate("Dialog", " Back  "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
